title: Guide méthodologique de licence de géographie 
description: Ce guide doit vous accompagner dans l’acquisition des connaissances socles et des savoir-faire essentiels en géographie. Sa consultation est conseillée de la 1ère à la 3e année de licence, mais ne doit pas remplacer votre recherche personnelle et votre consultation de manuels et de dictionnaires universitaires.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
